debug: true

common_db:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver
  user: common
  password: hello-common
  url: jdbc:postgresql://common-replica-1.cdawj8qazvva.us-east-1.rds.amazonaws.com:5432/common

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

#research_db:
#  driverClass: org.postgresql.Driver
#  user: research_user
#  password: hello-research-user
#  url: jdbc:postgresql://research.cdawj8qazvva.us-east-1.rds.amazonaws.com:5432/research
#  # any properties specific to your JDBC driver:
#  properties:
#    charSet: UTF-8

server:
  adminMinThreads: 1
  adminMaxThreads: 64
  adminContextPath: /
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 9987
  adminConnectors:
    - type: http
      port: 9988
  requestLog:
    appenders:
      - type: console

logging:
  level: INFO
  loggers:
    com.hello.suripu.app: INFO
    com.hello.suripu.core: DEBUG
    com.amazonaws: WARN
  appenders:
     - type: console

timeline_algorithm_configuration:
  artificial_light_start_time: "21:30"
  artificial_light_stop_time: "05:00"

# store sleep scores and other stats
# v0.2: score uses movement and duration
sleep_stats_version: v_0_2


timeline_model_ensembles:
  bucket: hello-timeline-models
  key: normal4ensemble.base64

timeline_seed_model:
  bucket: hello-timeline-models
  key: normal4.base64

taimurain_http_client:
  endpoint: http://internal-taimurain-prod-1606459001.us-east-1.elb.amazonaws.com:80
  http_client_config:
    keepAlive: 0s
    timeout: 10000ms

dynamodb:
  region: us-east-1
  tables:
    agg_stats: agg_stats
    alarm: alarm
    alarm_info: alarm_info
    algorithm_test: algorithm_test
    app_stats: app_stats
    calibration: prod_calibration
    device_data: prod_sense_data
    feature_extraction_models: feature_extraction_models
    features: features
    file_manifest: file_manifest
    insights: insights
    insights_last_seen: insights_last_seen
    marketing_insights_seen: marketing_insights_seen
    notifications: notifications
    online_hmm_models: online_hmm_models
    ota_history: ota_history
    password_reset: password_reset
    pill_data: prod_pill_data
    pill_heartbeat: pill_heartbeat
    pill_key_store: pill_key_store
    preferences: preferences
    profile_photo: profile_photo
    push_notification_event: push_notification_event
    ring_time: ring_time
    ring_time_history: ring_history_by_account
    sense_events: event
    sense_key_store: key_store
    sense_last_seen: sense_last_seen
    sense_state: sense_state
    sleep_hmm: sleephmm
    sleep_score: sleep_score
    sleep_score_parameters: sleep_score_parameters
    sleep_stats: sleep_stats
    smart_alarm_log: smart_alarm_log
    speech_results: speech_results
    speech_timeline: speech_timeline
    swap_intents: swap_intents
    sync_response_commands: response_commands
    teams: teams
    timeline: timeline
    timeline_log: timeline_log
    timezone_history: timezone_history
    wifi_info: wifi_info
  endpoints:
    agg_stats: http://localhost:7777
    alarm: http://localhost:7777
    alarm_info: http://localhost:7777
    algorithm_test: http://localhost:7777
    app_stats: http://localhost:7777
    calibration: http://dynamodb.us-east-1.amazonaws.com
    device_data: http://dynamodb.us-east-1.amazonaws.com
    feature_extraction_models: http://localhost:7777
    features: http://localhost:7777
    file_manifest: http://localhost:7777
    insights: http://localhost:7777
    insights_last_seen: http://localhost:7777
    marketing_insights_seen: http://localhost:7777
    notifications: http://localhost:7777
    online_hmm_models: http://localhost:7777
    ota_history: http://localhost:7777
    password_reset: http://localhost:7777
    pill_data: http://dynamodb.us-east-1.amazonaws.com
    pill_heartbeat: http://localhost:7777
    pill_key_store: http://localhost:7777
    preferences: http://localhost:7777
    profile_photo: http://localhost:7777
    push_notification_event: http://localhost:7777
    ring_time_history: http://localhost:7777
    sense_key_store: http://localhost:7777
    sense_last_seen: http://localhost:7777
    sleep_hmm: http://localhost:7777
    sense_state: http://localhost:7777
    sleep_score: http://localhost:7777
    sleep_score_parameters: http://localhost:7777
    sleep_stats: http://localhost:7777
    smart_alarm_log: http://localhost:7777
    speech_results: http://localhost:7777
    speech_timeline: http://localhost:7777
    swap_intents: http://localhost:7777
    sync_response_commands: http://localhost:7777
    timeline: http://localhost:7777
    timeline_log: http://localhost:7777
    timezone_history: http://localhost:7777
    wifi_info: http://localhost:7777
